swagger: "2.0"
info:
    title: Weather Forecast Service API
    description: The weather forecast service API produces weather forecasts from US-based IPs. It uses IP location to find the appropriate weather station.
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /forecast/{ip}:
        get:
            tags:
                - front
            summary: forecast front
            description: Retrieve weather forecast for given IP
            operationId: front#forecast
            parameters:
                - name: ip
                  in: path
                  required: true
                  type: string
                  format: ip
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/FrontForecastResponseBody'
                        required:
                            - location
                            - periods
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/FrontForecastNotUsaResponseBody'
            schemes:
                - http
    /tester/all:
        post:
            tags:
                - front
            summary: test_all front
            description: Endpoint for running API Integration Tests for the Weather System
            operationId: front#test_all
            parameters:
                - name: test_all_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/FrontTestAllRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/FrontTestAllResponseBody'
                        required:
                            - collections
                            - duration
                            - pass_count
                            - fail_count
            schemes:
                - http
    /tester/smoke:
        post:
            tags:
                - front
            summary: test_smoke front
            description: Endpoint for running API Integration Tests for the Weather System
            operationId: front#test_smoke
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/FrontTestSmokeResponseBody'
                        required:
                            - collections
                            - duration
                            - pass_count
                            - fail_count
            schemes:
                - http
definitions:
    FrontForecastNotUsaResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: IP address is not in the US (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    FrontForecastResponseBody:
        title: FrontForecastResponseBody
        type: object
        properties:
            location:
                $ref: '#/definitions/LocationResponseBody'
            periods:
                type: array
                items:
                    $ref: '#/definitions/PeriodResponseBody'
                description: Weather forecast periods
                example:
                    - endTime: "2020-01-01T00:00:00Z"
                      name: Morning
                      startTime: "2020-01-01T00:00:00Z"
                      summary: Clear
                      temperature: 70
                      temperatureUnit: F
                    - endTime: "2020-01-01T00:00:00Z"
                      name: Morning
                      startTime: "2020-01-01T00:00:00Z"
                      summary: Clear
                      temperature: 70
                      temperatureUnit: F
        example:
            location:
                city: San Francisco
                lat: 37.8267
                long: -122.4233
                state: CA
            periods:
                - endTime: "2020-01-01T00:00:00Z"
                  name: Morning
                  startTime: "2020-01-01T00:00:00Z"
                  summary: Clear
                  temperature: 70
                  temperatureUnit: F
                - endTime: "2020-01-01T00:00:00Z"
                  name: Morning
                  startTime: "2020-01-01T00:00:00Z"
                  summary: Clear
                  temperature: 70
                  temperatureUnit: F
                - endTime: "2020-01-01T00:00:00Z"
                  name: Morning
                  startTime: "2020-01-01T00:00:00Z"
                  summary: Clear
                  temperature: 70
                  temperatureUnit: F
        required:
            - location
            - periods
    FrontTestAllRequestBody:
        title: FrontTestAllRequestBody
        type: object
        properties:
            exclude:
                type: array
                items:
                    type: string
                    example: Iste eveniet.
                description: Tests to exclude
                example:
                    - Architecto minima molestiae ad unde.
                    - Porro possimus iste eius minus nesciunt.
                    - Dolores ducimus.
            include:
                type: array
                items:
                    type: string
                    example: Temporibus ex quo nihil rem.
                description: Tests to run
                example:
                    - Et itaque itaque cupiditate voluptas quod.
                    - Sequi ipsum vitae ut impedit.
                    - Officiis asperiores rem consequatur.
                    - Architecto aperiam odit.
        example:
            exclude:
                - Nihil cum.
                - Amet consequatur.
                - Quis sint alias.
            include:
                - Sequi sit molestiae pariatur nam saepe.
                - Dolorem inventore porro velit.
                - Iste dolorem.
                - Quibusdam in dolor error amet ut debitis.
    FrontTestAllResponseBody:
        title: FrontTestAllResponseBody
        type: object
        properties:
            collections:
                type: array
                items:
                    $ref: '#/definitions/TestCollectionResponseBody'
                description: Test collections
                example:
                    - duration: 9054733701520478298
                      fail_count: 7502424151970560367
                      name: Id necessitatibus consequatur a laudantium quia qui.
                      pass_count: 8417812319446678629
                      results:
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                    - duration: 9054733701520478298
                      fail_count: 7502424151970560367
                      name: Id necessitatibus consequatur a laudantium quia qui.
                      pass_count: 8417812319446678629
                      results:
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                    - duration: 9054733701520478298
                      fail_count: 7502424151970560367
                      name: Id necessitatibus consequatur a laudantium quia qui.
                      pass_count: 8417812319446678629
                      results:
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                    - duration: 9054733701520478298
                      fail_count: 7502424151970560367
                      name: Id necessitatibus consequatur a laudantium quia qui.
                      pass_count: 8417812319446678629
                      results:
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
            duration:
                type: integer
                description: Duration of the tests in ns
                example: 8488659046950973621
                format: int64
            fail_count:
                type: integer
                description: Number of tests that failed
                example: 4437501359757801476
                format: int64
            pass_count:
                type: integer
                description: Number of tests that passed
                example: 4542181070557550195
                format: int64
        example:
            collections:
                - duration: 9054733701520478298
                  fail_count: 7502424151970560367
                  name: Id necessitatibus consequatur a laudantium quia qui.
                  pass_count: 8417812319446678629
                  results:
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                - duration: 9054733701520478298
                  fail_count: 7502424151970560367
                  name: Id necessitatibus consequatur a laudantium quia qui.
                  pass_count: 8417812319446678629
                  results:
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                - duration: 9054733701520478298
                  fail_count: 7502424151970560367
                  name: Id necessitatibus consequatur a laudantium quia qui.
                  pass_count: 8417812319446678629
                  results:
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
            duration: 4227364704972892770
            fail_count: 677188132726143600
            pass_count: 7256829688975880749
        required:
            - collections
            - duration
            - pass_count
            - fail_count
    FrontTestSmokeResponseBody:
        title: FrontTestSmokeResponseBody
        type: object
        properties:
            collections:
                type: array
                items:
                    $ref: '#/definitions/TestCollectionResponseBody'
                description: Test collections
                example:
                    - duration: 9054733701520478298
                      fail_count: 7502424151970560367
                      name: Id necessitatibus consequatur a laudantium quia qui.
                      pass_count: 8417812319446678629
                      results:
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                    - duration: 9054733701520478298
                      fail_count: 7502424151970560367
                      name: Id necessitatibus consequatur a laudantium quia qui.
                      pass_count: 8417812319446678629
                      results:
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
                        - duration: 859505013544304124
                          error: Consectetur eos nihil accusamus reiciendis eligendi.
                          name: Dolorem nam quisquam laudantium incidunt ipsa.
                          passed: true
            duration:
                type: integer
                description: Duration of the tests in ns
                example: 3276831852005724953
                format: int64
            fail_count:
                type: integer
                description: Number of tests that failed
                example: 7444985474897945228
                format: int64
            pass_count:
                type: integer
                description: Number of tests that passed
                example: 7568645513158539910
                format: int64
        example:
            collections:
                - duration: 9054733701520478298
                  fail_count: 7502424151970560367
                  name: Id necessitatibus consequatur a laudantium quia qui.
                  pass_count: 8417812319446678629
                  results:
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                - duration: 9054733701520478298
                  fail_count: 7502424151970560367
                  name: Id necessitatibus consequatur a laudantium quia qui.
                  pass_count: 8417812319446678629
                  results:
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                - duration: 9054733701520478298
                  fail_count: 7502424151970560367
                  name: Id necessitatibus consequatur a laudantium quia qui.
                  pass_count: 8417812319446678629
                  results:
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                - duration: 9054733701520478298
                  fail_count: 7502424151970560367
                  name: Id necessitatibus consequatur a laudantium quia qui.
                  pass_count: 8417812319446678629
                  results:
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
            duration: 3974704679362411249
            fail_count: 5538145994199568149
            pass_count: 3830990445097321547
        required:
            - collections
            - duration
            - pass_count
            - fail_count
    LocationResponseBody:
        title: LocationResponseBody
        type: object
        properties:
            city:
                type: string
                description: City
                example: San Francisco
            lat:
                type: number
                description: Latitude
                example: 37.8267
                format: double
            long:
                type: number
                description: Longitude
                example: -122.4233
                format: double
            state:
                type: string
                description: State
                example: CA
        description: Geographical location
        example:
            city: San Francisco
            lat: 37.8267
            long: -122.4233
            state: CA
        required:
            - lat
            - long
            - city
            - state
    PeriodResponseBody:
        title: PeriodResponseBody
        type: object
        properties:
            endTime:
                type: string
                description: End time
                example: "2020-01-01T00:00:00Z"
                format: date-time
            name:
                type: string
                description: Period name
                example: Morning
            startTime:
                type: string
                description: Start time
                example: "2020-01-01T00:00:00Z"
                format: date-time
            summary:
                type: string
                description: Summary
                example: Clear
            temperature:
                type: integer
                description: Temperature
                example: 70
                format: int64
            temperatureUnit:
                type: string
                description: Temperature unit
                example: F
        description: Weather forecast period
        example:
            endTime: "2020-01-01T00:00:00Z"
            name: Morning
            startTime: "2020-01-01T00:00:00Z"
            summary: Clear
            temperature: 70
            temperatureUnit: F
        required:
            - name
            - startTime
            - endTime
            - temperature
            - temperatureUnit
            - summary
    TestCollectionResponseBody:
        title: TestCollectionResponseBody
        type: object
        properties:
            duration:
                type: integer
                description: Duration of the tests in ns
                example: 8853997182033955550
                format: int64
            fail_count:
                type: integer
                description: Number of tests that failed
                example: 1059133839524475990
                format: int64
            name:
                type: string
                description: Name of the test collection
                example: Vel inventore.
            pass_count:
                type: integer
                description: Number of tests that passed
                example: 5893583093005980628
                format: int64
            results:
                type: array
                items:
                    $ref: '#/definitions/TestResultResponseBody'
                description: Test results
                example:
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
                    - duration: 859505013544304124
                      error: Consectetur eos nihil accusamus reiciendis eligendi.
                      name: Dolorem nam quisquam laudantium incidunt ipsa.
                      passed: true
        description: Collection of test results for grouping by service
        example:
            duration: 8938474736767396736
            fail_count: 5612515089578572696
            name: Sit quis aut deleniti tenetur.
            pass_count: 7491432401091584119
            results:
                - duration: 859505013544304124
                  error: Consectetur eos nihil accusamus reiciendis eligendi.
                  name: Dolorem nam quisquam laudantium incidunt ipsa.
                  passed: true
                - duration: 859505013544304124
                  error: Consectetur eos nihil accusamus reiciendis eligendi.
                  name: Dolorem nam quisquam laudantium incidunt ipsa.
                  passed: true
                - duration: 859505013544304124
                  error: Consectetur eos nihil accusamus reiciendis eligendi.
                  name: Dolorem nam quisquam laudantium incidunt ipsa.
                  passed: true
                - duration: 859505013544304124
                  error: Consectetur eos nihil accusamus reiciendis eligendi.
                  name: Dolorem nam quisquam laudantium incidunt ipsa.
                  passed: true
        required:
            - name
            - results
            - duration
            - pass_count
            - fail_count
    TestResultResponseBody:
        title: TestResultResponseBody
        type: object
        properties:
            duration:
                type: integer
                description: Duration of the test in ns
                example: 4825182501324116159
                format: int64
            error:
                type: string
                description: Error message if the test failed
                example: Tempora tenetur.
            name:
                type: string
                description: Name of the test
                example: Ab nulla ad in optio sed.
            passed:
                type: boolean
                description: Status of the test
                example: true
        description: Test result for a single test
        example:
            duration: 6032363257340067070
            error: Omnis vel quia ab dolorem qui.
            name: Asperiores est.
            passed: true
        required:
            - name
            - passed
            - duration
